### ISSUE TITLE
Neverland Context codepen broken since version 1.2.0

### ISSUE THREAD

**Issue by mheinz67** [WebReflection/neverland#16]
Running the codepen https://codepen.io/dakom/pen/QzRmar results in an error
since version 1.2.0

Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Y (https://unpkg.com/neverland@1.2.3/min.js:2:7794)
    at ie (https://unpkg.com/neverland@1.2.3/min.js:2:10350)
    at Array.o (https://unpkg.com/neverland@1.2.3/min.js:2:16770)
    at https://unpkg.com/neverland@1.2.3/min.js:2:13699
    at https://unpkg.com/neverland@1.2.3/min.js:2:13990
    at t.(anonymous function) (https://unpkg.com/neverland@1.2.3/min.js:2:17568)
    at https://unpkg.com/neverland@1.2.3/min.js:2:17328
    at children.map.child (pen.js:61:35)
    at Array.map (<anonymous>)
    at children (pen.js:61:18)

**Comment by WebReflection** [comment]
This works for me:
https://codepen.io/WebReflection/pen/QYOZZE?editors=0010

Basically you don't need to use `component` if you don't use any feature.

**Comment by mheinz67** [comment]
Hi Andrea,

please update codepen.md with the working codepen.

**Comment by WebReflection** [comment]
good call, done 👋
